export const destinations = [
  {
    name: "France",
    flag: "🇫🇷",
    image: "/images/home/destinations/france.jpg",
    languages: ["French", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/france",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Germany",
    flag: "🇩🇪",
    image: "/images/home/destinations/germany.jpg",
    languages: ["German", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/germany",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Italy",
    flag: "🇮🇹",
    image: "/images/home/destinations/italy.jpg",
    languages: ["Italian", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/italy",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Canada",
    flag: "🇨🇦",
    image: "/images/home/destinations/canada.jpg",
    languages: ["English", "French"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/canada",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Turkey",
    flag: "🇹🇷",
    image: "/images/home/destinations/turkey.jpg",
    languages: ["Turkish", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/turkey",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Netherlands",
    flag: "🇳🇱",
    image: "/images/home/destinations/netherlands.jpg",
    languages: ["Dutch", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/netherlands",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Spain",
    flag: "🇪🇸",
    image: "/images/home/destinations/spain.jpg",
    languages: ["Spanish", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/spain",
    scholarships: true,
    visaRequired: true,
  },
];

export const scholarships = [
  {
    name: "Erasmus Mundus Joint Masters",
    country: "Europe",
    flag: "🇪🇺",
    level: "Master",
    funding: "Fully funded scholarship for international students.",
    deadline: "January 2027",
    image: "/images/home/scholarships/erasmus-mundus.jpg",
    href: "/scholarships/erasmus-mundus",
  },
  {
    name: "DAAD EPOS",
    country: "Germany",
    flag: "🇩🇪",
    level: "Master",
    funding: "Funding for development-related postgraduate programs.",
    deadline: "Varies by program",
    image: "/images/home/scholarships/daad-epos.jpg",
    href: "/scholarships/daad-epos",
  },
  {
    name: "Eiffel Excellence Scholarship",
    country: "France",
    flag: "🇫🇷",
    level: "Master",
    funding: "French government scholarship for international students.",
    deadline: "January 2027",
    image: "/images/home/scholarships/eiffel.jpg",
    href: "/scholarships/eiffel",
  },
];
