import {
  TrendingUp,
  Globe,
  BookOpen,
  FileText,
  Award,
  Plane,
  Bot,
} from "lucide-react";

export const destinations = [
  {
    name: "France",
    flag: "🇫🇷",
    image: "/images/home/destinations/france.jpg",
    languages: ["French", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/france",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Germany",
    flag: "🇩🇪",
    image: "/images/home/destinations/germany.jpg",
    languages: ["German", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/germany",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Italy",
    flag: "🇮🇹",
    image: "/images/home/destinations/italy.jpg",
    languages: ["Italian", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/italy",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Canada",
    flag: "🇨🇦",
    image: "/images/home/destinations/canada.jpg",
    languages: ["English", "French"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/canada",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Turkey",
    flag: "🇹🇷",
    image: "/images/home/destinations/turkey.jpg",
    languages: ["Turkish", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/turkey",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Netherlands",
    flag: "🇳🇱",
    image: "/images/home/destinations/netherlands.jpg",
    languages: ["Dutch", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/netherlands",
    scholarships: true,
    visaRequired: true,
  },
  {
    name: "Spain",
    flag: "🇪🇸",
    image: "/images/home/destinations/spain.jpg",
    languages: ["Spanish", "English"],
    levels: ["Bachelor", "Master", "PhD"],
    href: "/study-abroad/spain",
    scholarships: true,
    visaRequired: true,
  },
];

export const scholarships = [
  {
    name: "Erasmus Mundus Joint Masters",
    country: "Europe",
    flag: "🇪🇺",
    level: "Master",
    funding: "Fully funded scholarship for international students.",
    deadline: "January 2027",
    image: "/images/home/scholarships/erasmus-mundus.jpg",
    href: "/scholarships/erasmus-mundus",
  },
  {
    name: "DAAD EPOS",
    country: "Germany",
    flag: "🇩🇪",
    level: "Master",
    funding: "Funding for development-related postgraduate programs.",
    deadline: "Varies by program",
    image: "/images/home/scholarships/daad-epos.jpg",
    href: "/scholarships/daad-epos",
  },
  {
    name: "Eiffel Excellence Scholarship",
    country: "France",
    flag: "🇫🇷",
    level: "Master",
    funding: "French government scholarship for international students.",
    deadline: "January 2027",
    image: "/images/home/scholarships/eiffel.jpg",
    href: "/scholarships/eiffel",
  },
];

export const quickCategories = [
  {
    icon: TrendingUp,
    label: "Find My Study Path",
    desc: "Get a personalized step-by-step path for your goal.",
    href: "/find-my-path",
    accent: "bg-[#eaf0ff] text-[#3157d5]",
  },
  {
    icon: Globe,
    label: "Explore Countries",
    desc: "Compare admission, costs, and visas by destination.",
    href: "/study-abroad",
    accent: "bg-[#e7f8f4] text-[#0f9f8f]",
  },
  {
    icon: BookOpen,
    label: "Admission Requirements",
    desc: "Know exactly what each country requires for your level.",
    href: "/admission-requirements",
    accent: "bg-[#eaf0ff] text-[#3157d5]",
  },
  {
    icon: FileText,
    label: "Required Documents",
    desc: "Every document explained, with prep guidance.",
    href: "/documents",
    accent: "bg-[#f0fdf4] text-[#16803a]",
  },
  {
    icon: Award,
    label: "Scholarships",
    desc: "Find funding that fits your path, level, and field.",
    href: "/scholarships",
    accent: "bg-[#fff5df] text-[#b76800]",
  },
  {
    icon: Plane,
    label: "Student Visa",
    desc: "Country-by-country visa guides with official steps.",
    href: "/student-visa",
    accent: "bg-[#eaf0ff] text-[#3157d5]",
  },
  {
    icon: Bot,
    label: "AI Study Navigator",
    desc: "Describe your situation — we'll organize your path.",
    href: "/ai-navigator",
    accent: "bg-slate-100 text-slate-600",
    badge: "AI-assisted",
  },
];
